package fakeproto_test

import (
	"testing"

	"github.com/brianvoe/gofakeit/v7"

	"github.com/psyhatter/fakeproto"
	testpb "github.com/psyhatter/fakeproto/internal/test/gen"
)

// validStatuses is the set of declared Status values, including the intentional
// negative value STATUS_DELETED = -1.
var validStatuses = map[testpb.Status]bool{
	testpb.Status_STATUS_UNSPECIFIED: true,
	testpb.Status_STATUS_ACTIVE:      true,
	testpb.Status_STATUS_INACTIVE:    true,
	testpb.Status_STATUS_SUSPENDED:   true,
	testpb.Status_STATUS_DELETED:     true,
}

var validPriorities = map[testpb.Priority]bool{
	testpb.Priority_PRIORITY_UNSPECIFIED: true,
	testpb.Priority_PRIORITY_LOW:         true,
	testpb.Priority_PRIORITY_MEDIUM:      true,
	testpb.Priority_PRIORITY_HIGH:        true,
}

func TestEnumsWithEnum(t *testing.T) {
	t.Parallel()

	msg := &testpb.WithEnum{}
	if err := fakeproto.Message(msg); err != nil {
		t.Fatal(err)
	}
	if !validStatuses[msg.GetStatus()] {
		t.Errorf("unexpected Status value %v", msg.GetStatus())
	}
	if !validPriorities[msg.GetPriority()] {
		t.Errorf("unexpected Priority value %v", msg.GetPriority())
	}
}

// TestEnumsNegativeValueReachable verifies that the generator can produce
// STATUS_DELETED=-1 across a number of runs with different seeds.
func TestEnumsNegativeValueReachable(t *testing.T) {
	t.Parallel()

	const limit uint64 = 200

	seen := false
	for seed := range limit {
		msg := &testpb.WithEnum{}
		if err := fakeproto.Message(msg, fakeproto.WithFaker(gofakeit.New(seed))); err != nil {
			t.Fatal(err)
		}
		if msg.GetStatus() == testpb.Status_STATUS_DELETED {
			seen = true
			break
		}
	}
	if !seen {
		t.Errorf("STATUS_DELETED=-1 was never generated across %d seeds", limit)
	}
}

func TestEnumsCollections(t *testing.T) {
	t.Parallel()

	msg := &testpb.EnumCollections{}
	if err := fakeproto.Message(msg); err != nil {
		t.Fatal(err)
	}
	if len(msg.GetStatuses()) == 0 {
		t.Error("EnumCollections.Statuses is empty")
	}
	for i, s := range msg.GetStatuses() {
		if !validStatuses[s] {
			t.Errorf("Statuses[%d]=%v is not a declared value", i, s)
		}
	}
	if len(msg.GetPriorityByName()) == 0 {
		t.Error("EnumCollections.PriorityByName is empty")
	}
	for k, p := range msg.GetPriorityByName() {
		if !validPriorities[p] {
			t.Errorf("PriorityByName[%q]=%v is not a declared value", k, p)
		}
	}
}

// TestEnumDirect exercises the Enum generic function on both Status and Priority.
func TestEnumDirect(t *testing.T) {
	t.Parallel()

	t.Run("Status", func(t *testing.T) {
		t.Parallel()
		var s testpb.Status
		fakeproto.Enum(&s)
		if !validStatuses[s] {
			t.Errorf("Status=%v is not a declared value", s)
		}
	})

	t.Run("Priority", func(t *testing.T) {
		t.Parallel()
		var p testpb.Priority
		fakeproto.Enum(&p)
		if !validPriorities[p] {
			t.Errorf("Priority=%v is not a declared value", p)
		}
	})

	// Verify STATUS_DELETED=-1 is reachable via Enum as well.
	t.Run("NegativeReachable", func(t *testing.T) {
		t.Parallel()
		seen := false
		const limit uint64 = 200
		for seed := range limit {
			var s testpb.Status
			fakeproto.Enum(&s, fakeproto.WithFaker(gofakeit.New(seed)))
			if s == testpb.Status_STATUS_DELETED {
				seen = true
				break
			}
		}
		if !seen {
			t.Errorf("STATUS_DELETED=-1 was never generated by Enum across %d seeds", limit)
		}
	})
}

func BenchmarkEnums(b *testing.B) {
	opt := fakeproto.WithFaker(gofakeit.New(0))
	b.ResetTimer()
	for range b.N {
		msg := &testpb.WithEnum{}
		_ = fakeproto.Message(msg, opt)
	}
}

func BenchmarkEnum(b *testing.B) {
	opt := fakeproto.WithFaker(gofakeit.New(0))
	b.ResetTimer()
	for range b.N {
		var s testpb.Status
		fakeproto.Enum(&s, opt)
	}
}

func FuzzEnums(f *testing.F) {
	f.Fuzz(func(t *testing.T, seed uint64) {
		t.Parallel()
		msg := &testpb.WithEnum{}
		if err := fakeproto.Message(msg, fakeproto.WithFaker(gofakeit.New(seed))); err != nil {
			t.Fatal(err)
		}
		if !validStatuses[msg.GetStatus()] {
			t.Errorf("unexpected Status value %v", msg.GetStatus())
		}
	})
}

func FuzzEnum(f *testing.F) {
	f.Fuzz(func(t *testing.T, seed uint64) {
		t.Parallel()
		var s testpb.Status
		fakeproto.Enum(&s, fakeproto.WithFaker(gofakeit.New(seed)))
		if !validStatuses[s] {
			t.Errorf("seed=%d: Status=%v is not a declared value", seed, s)
		}
	})
}
